### PR TITLE
Terraform Example Code Optimized

### PR DESCRIPTION
**Pull request by marifse**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by marifse** [comment]
@ocofaigh can you please review this too. Thanks

**Comment by Ak-sky** [comment]
In PR test `TestFSCloudInSchematics`, need to pass `region` and `prefix` variable value.

**Comment by marifse** [comment]
@ocofaigh can you please try rerun the pipeline, i have added the prefix value in test

**Comment by ocofaigh** [comment]
@marifse This has conflict again - to avoid this please do not commit updates to the common-dev-assets git submodule in your PRs

**Comment by marifse** [comment]
@ocofaigh can you kindly rerun the pipeline, have fixed the conflicts.

**Comment by ocofaigh** [comment]
@marifse can you address failing pre commit hooks please?
```
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing tests/go.mod
Fixing tests/go.sum
```

**Comment by ocofaigh** [comment]
@marifse Now that prefix and region are required variables, you will need to update the `TestFSCloudInSchematics` test [here](https://github.com/marifse/terraform-ibm-cbr/blob/456119bccfa0c5e0a8e806f25fea42c94e3f55c5/tests/pr_test.go#L298) to pass the prefix like so:

```
{Name: "prefix", Value: options.Prefix, DataType: "string"},
{Name: "region", Value: options.Region, DataType: "string"},
```

**Comment by marifse** [comment]
@ocofaigh variables added, can you please rerun

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
