### PR TITLE
test: modified pr_test and moved fscloud to other test

### PR DESCRIPTION
**Pull request by Ak-sky**
### Description

- Removed the RG from the pr test so that the target services will be scoped to newly created RGs.
- Moved the FScloud example to other test so that it does not clash with other PRs.

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Review by ocofaigh — COMMENTED** [review]
does removing the resource group make any difference if the fscloud example does not scope its rules?

**Comment by Ak-sky** [comment]
> does removing the resource group make any difference if the fscloud example does not scope its rules?

Yes, for other examples other than fscloud, removing resource group is required.
For fscloud example we definitely need enterprise sub account.

**Comment by ocofaigh** [comment]
@Ak-sky OK so please create update this PT with just the remove of the resource group. I think we said its too risky to move the fscloud example to other_test.go since there will be too much of a test gap right?

**Pull request closed without merging**
