### PR TITLE
test: update fscloud test

### PR DESCRIPTION
**Pull request by iamar7**
### Description
Update the FSCloud test to run in schematics workspace
https://github.ibm.com/GoldenEye/issues/issues/7984

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
@Ak-sky Any idea why the `TestMultiServiceProfileExample` test would fail with:
```
"Invalid `serviceRef` location: `us-south` is invalid. Allowed values for each service can be found using the list service reference targets API."
```

This PR did not make any chances to that test

**Comment by Ak-sky** [comment]
> @Ak-sky Any idea why the `TestMultiServiceProfileExample` test would fail with:
> 
> ```
> "Invalid `serviceRef` location: `us-south` is invalid. Allowed values for each service can be found using the list service reference targets API."
> ```
> 
> This PR did not make any chances to that test

@ocofaigh 
I figured there are 2 issues -
1. This PR is failing because in `multi-service-profile` example we are passing location as well for the creation of serviceRef zones, we are setting `us-south` location for each of the passed serviceRef, looks like it is now taking value as `us` and not `us-south`, I have also posted [message](https://ibm-cloudplatform.slack.com/archives/C01U169P12P/p1711550096016699) in the #cbr-adopters channel regarding this change. Looks like there are some segregation with respect to CBR location/region names, for example, US location names below which I gathered from this [List available service reference targets](https://cloud.ibm.com/apidocs/context-based-restrictions#list-available-serviceref-targets) API response -

```
       {
          "display_name": "North America",
          "kind": "geography",
          "name": "na"
        },
        {
          "display_name": "United States",
          "kind": "country",
          "name": "us"
        },
        {
          "display_name": "Dallas",
          "kind": "metro",
          "name": "dal"
        },
        {
          "display_name": "Washington DC",
          "kind": "metro",
          "name": "wdc"
        },
        {
          "display_name": "South America",
          "kind": "geography",
          "name": "sa"
        },
```
2. Also this `multi-service-profile` example should be failing as this logic [here](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/blob/c6032c999f65c8fd958df526a4dc256a97388db6/modules/cbr-service-profile/main.tf#L15) is wrong.

**Comment by Ak-sky** [comment]
Raised [this](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/pull/423) PR as a fix.

**Review by Ak-sky — APPROVED** [review]

**Pull request merged**
