### PR TITLE
fix: remove public default context

### PR DESCRIPTION
**Pull request by iamar7**
### Description

https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/349

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Ak-sky** [comment]
As per the discussion with Vincent, here the requirement is-

- Remove default deny context only but need to have none context in rules for all the target services.

**Comment by iamar7** [comment]
Closing this PR since the changes have already been taken care in this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/pull/396) by @Aashiq-J

**Pull request closed without merging**
