### PR TITLE
fix: multi-service-profile example

### LINKED ISSUE #220: Adjust multi-service-profile example
### Description

Couple of issues with this example:
- The README.md is not fully accurate. It refers to "the module's default variable values" which is not fully accurate. Also it actually demonstrates the submodule https://github.com/terraform-ibm-modules/terraform-ibm-cbr/tree/main/cbr-service-profile
- The CBR topology that is creates, which working, does not really makes sense in a real world scenario.
   - The current topology creates 3 rules (object storage, message hub, kms) and for each of those rules, it adds as a zone a VPC + 2 services (direct link and intrastructure services). I do not think of any real world scenario where direct link would need to be able to access to object storage, message hub or kms in this account. 
- I'd suggest aligning the example on the actual flow that exists in landing zone  / fscloud topology - eg:
image

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Ak-sky**
### Description

Fixed multi-service-profile example.

fixes #220 

#### Changes that affect the core Terraform module or submodules
- [ ] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [x] Examples or tests (addition or updates of examples or tests)
- [x] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.

Your notes help the merger write the commit message for the PR that is published in the release notes for the module.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Review by vburckhardt — APPROVED** [review]

**Comment by vburckhardt** [comment]
Looking good - thanks for addressing the comment.

**Comment by vburckhardt** [comment]
Pipeline failed with 

> TestRunCompleteExample 2023-07-18T10:41:46Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
> │ Error: DeleteZoneWithContext failed The network zone 'd580e35011401452b797d42d19ce0bef' is referenced by one or more rules and cannot be deleted.
> │ {
> │     "StatusCode": 412,
> │     "Headers": {
> │         "Akamai-Grn": [
> │             "0.176adc17.1689676893.1006d30"
> │         ],
> │         "Cache-Control": [
> │             "no-cache,no-store"
> │         ],
> │         "Connection": [
> │             "keep-alive"
> │         ],
> │         "Content-Length": [
> │             "228"
> │         ],
> │         "Content-Type": [
> │             "application/json; charset=utf-8"
> │         ],
> │         "Date": [
> │             "Tue, 18 Jul 2023 10:41:33 GMT"
> │         ],
> │         "Expires": [
> │             "Thursday, 1 January 1970 00:00:00 GMT"
> │         ],
> │         "Pragma": [
> │             "no-cache"
> │         ],
> │         "Set-Cookie": [
> │             "ak_bmsc=6E06E5EABA70A1AD02D3A09E0BED6F4D~000000000000000000000000000000~YAAQF2rcF6QhF2iJAQAAeU6XaBTk9JX17SckVPg0sVSdQ8Q1BvWZBzChGxFBh+hzcWTQGqbLo8cTrYBPuozpwkiGrM7RygtNJInNQfSaA0y6IPV3gV4DY5BBb7kY75p8ZLnmmSWS9kIZ3L79PfKBjKRYTxLFpWaDtzxVB0hOngOW43RChDOPlOgopsZnQGzHAmfF8omhCJK3x9h6P4Egp0w6wp7wG4eyWMgPhqLCpZcGZaLGONmKqIIFsybH0GORfwUycV8oWezbcYRiZQHP2m5OwTq/za3zOn9RunqSH1TP+9OCsdfKgBhiESziGK8zPLzWoE7+Q8Fg0n0gLEkmZmldqk1txabkapOfXhc3dBu6wKM+7pw9pFXpznEzHjATNGGpV0M=; Domain=.cloud.ibm.com; Path=/; Expires=Tue, 18 Jul 2023 12:41:33 GMT; Max-Age=7200; HttpOnly"
> │         ],
> │         "Strict-Transport-Security": [
> │             "max-age=31536000; includeSubDomains"
> │         ],
> │         "Transaction-Id": [
> │             "6de75a8f-9bcb-4e6b-acab-e3e555758db2"
> │         ],
> │         "X-Content-Type-Options": [
> │             "nosniff"
> │         ],
> │         "X-Correlation-Id": [
> │             "6de75a8f-9bcb-4e6b-acab-e3e555758db2"
> │         ],
> │         "X-Proxy-Upstream-Service-Time": [
> │             "285"
> │         ],
> │         "X-Ratelimit-Limit": [
> │             "10"
> │         ],
> │         "X-Ratelimit-Remaining": [
> │             "9"
> │         ],
> │         "X-Ratelimit-Reset": [
> │             "1689676894"
> │         ]
> │     },
> │     "Result": {
> │         "errors": [
> │             {
> │                 "code": "zone_used_by_rule",
> │                 "message": "The network zone 'd580e35011401452b797d42d19ce0bef' is referenced by one or more rules and cannot be deleted."
> │             }
> │         ],
> │         "status_code": 412,
> │         "trace": "6de75a8f-9bcb-4e6b-acab-e3e555758db2"
> │     },
> │     "RawResult": null
> │ }
> │ 
> │ 
> │ 
> ╵}
> === NAME  TestRunCompleteExample
>     destroy.go:11: 
>         	Error Trace:	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.43.8/modules/terraform/destroy.go:11
>         	            				/go/pkg/mod/github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper@v1.10.10/testhelper/tests.go:201
>         	            				/go/pkg/mod/github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper@v1.10.10/testhelper/tests.go:174
>         	Error:      	Received unexpected error:
>         	            	FatalError{Underlying: error while running command: exit status 1; ╷
>         	            	│ Error: DeleteZoneWithContext failed The network zone 'd580e35011401452b797d42d19ce0bef' is referenced by one or more rules and cannot be deleted.
>         	            	│ {
>         	            	│     "StatusCode": 412,
>         	            	│     "Headers": {
>         	            	│         "Akamai-Grn": [
>         	            	│             "0.176adc17.1689676893.1006d30"
>         	            	│         ],
>         	            	│         "Cache-Control": [
>         	            	│             "no-cache,no-store"
>         	            	│         ],
>         	            	│         "Connection": [
>         	            	│             "keep-alive"
>         	            	│         ],
>         	            	│         "Content-Length": [
>         	            	│             "228"
>         	            	│         ],
>         	            	│         "Content-Type": [
>         	            	│             "application/json; charset=utf-8"
>         	            	│         ],
>         	            	│         "Date": [
>         	            	│             "Tue, 18 Jul 2023 10:41:33 GMT"
>         	            	│         ],
>         	            	│         "Expires": [
>         	            	│             "Thursday, 1 January 1970 00:00:00 GMT"
>         	            	│         ],
>         	            	│         "Pragma": [
>         	            	│             "no-cache"
>         	            	│         ],
>         	            	│         "Set-Cookie": [
>         	            	│             "ak_bmsc=6E06E5EABA70A1AD02D3A09E0BED6F4D~000000000000000000000000000000~YAAQF2rcF6QhF2iJAQAAeU6XaBTk9JX17SckVPg0sVSdQ8Q1BvWZBzChGxFBh+hzcWTQGqbLo8cTrYBPuozpwkiGrM7RygtNJInNQfSaA0y6IPV3gV4DY5BBb7kY75p8ZLnmmSWS9kIZ3L79PfKBjKRYTxLFpWaDtzxVB0hOngOW43RChDOPlOgopsZnQGzHAmfF8omhCJK3x9h6P4Egp0w6wp7wG4eyWMgPhqLCpZcGZaLGONmKqIIFsybH0GORfwUycV8oWezbcYRiZQHP2m5OwTq/za3zOn9RunqSH1TP+9OCsdfKgBhiESziGK8zPLzWoE7+Q8Fg0n0gLEkmZmldqk1txabkapOfXhc3dBu6wKM+7pw9pFXpznEzHjATNGGpV0M=; Domain=.cloud.ibm.com; Path=/; Expires=Tue, 18 Jul 2023 12:41:33 GMT; Max-Age=7200; HttpOnly"
>         	            	│         ],
>         	            	│         "Strict-Transport-Security": [
>         	            	│             "max-age=31536000; includeSubDomains"
>         	            	│         ],
>         	            	│         "Transaction-Id": [
>         	            	│             "6de75a8f-9bcb-4e6b-acab-e3e555758db2"
>         	            	│         ],
>         	            	│         "X-Content-Type-Options": [
>         	            	│             "nosniff"
>         	            	│         ],
>         	            	│         "X-Correlation-Id": [
>         	            	│             "6de75a8f-9bcb-4e6b-acab-e3e555758db2"
>         	            	│         ],
>         	            	│         "X-Proxy-Upstream-Service-Time": [
>         	            	│             "285"
>         	            	│         ],
>         	            	│         "X-Ratelimit-Limit": [
>         	            	│             "10"
>         	            	│         ],
>         	            	│         "X-Ratelimit-Remaining": [
>         	            	│             "9"
>         	            	│         ],
>         	            	│         "X-Ratelimit-Reset": [
>         	            	│             "1689676894"
>         	            	│         ]
>         	            	│     },
>         	            	│     "Result": {
>         	            	│         "errors": [
>         	            	│             {
>         	            	│                 "code": "zone_used_by_rule",
>         	            	│                 "message": "The network zone 'd580e35011401452b797d42d19ce0bef' is referenced by one or more rules and cannot be deleted."
>         	            	│             }
>         	            	│         ],
>         	            	│         "status_code": 412,
>         	            	│         "trace": "6de75a8f-9bcb-4e6b-acab-e3e555758db2"
>         	            	│     },
>         	            	│     "RawResult": null
>         	            	│ }
>         	            	│ 
>         	            	│ 
>         	            	│ 
>         	            	╵}
>         	Test:       	TestRunCompleteExample
> --- FAIL: TestRunCompleteExample (122.70s)
>     --- PASS: TestRunCompleteExample/verify_all_zone_ids_exist (0.00s)
>     --- PASS: TestRunCompleteExample/verify_all_attributes_set (0.00s)
>     --- PASS: TestRunCompleteExample/verify_all_tags_present (0.00s)
>     --- PASS: TestRunCompleteExample/verify_no_operation_set (0.00s)

**Comment by Ak-sky** [comment]
Again [Pipeline failed](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/actions/runs/5589161597/jobs/10217127719) with PROVIDER ERROR below - 

> TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: ibm_is_subnet.testacc_subnet: Creation complete after 12s [id=0787-6e0bc973-9b7d-4563-9060-b3039578ff39]
TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: ╷
TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: │ Error: Provider produced inconsistent result after apply
TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: │ 
TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: │ When applying changes to module.ibm_cbr_zone.ibm_cbr_zone.cbr_zone,
TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: │ provider "provider[\"registry.terraform.io/ibm-cloud/ibm\"]" produced an
TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: │ unexpected new value: Root resource was present, but now absent.
TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: │ 
TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: │ This is a bug in the provider, which should be reported in the provider's
TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: │ own issue tracker.
TestRunZoneExample 2023-07-18T15:13:32Z logger.go:66: ╵
TestRunZoneExample 2023-07-18T15:13:32Z retry.go:144: 'terraform [apply -input=false -auto-approve -var resource_tags=[] -var prefix=cbr-zone-y89gs0 -var region=eu-gb -var resource_group=geretain-test-cbr -lock=false]' failed with the error 'error while running command: exit status 1; ╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.ibm_cbr_zone.ibm_cbr_zone.cbr_zone,
│ provider "provider[\"registry.terraform.io/ibm-cloud/ibm\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵' but this error was expected and warrants a retry. Further details: Provider eventual consistency error.

**Pull request merged**
